/**** Creation of Schemas ****/
GO
IF NOT EXISTS (SELECT [SCHEMA_NAME]
              FROM GHGandAGR.INFORMATION_SCHEMA.SCHEMATA
			  WHERE[SCHEMA_NAME] = 'dim'
			  )
exec('CREATE SCHEMA dim')
;
GO 
IF NOT EXISTS (SELECT [SCHEMA_NAME]
              FROM GHGandAGR.INFORMATION_SCHEMA.SCHEMATA
			  WHERE[SCHEMA_NAME] = 'stg'
			  )
exec('CREATE SCHEMA stg')
;
GO 
IF NOT EXISTS (SELECT [SCHEMA_NAME]
              FROM GHGandAGR.INFORMATION_SCHEMA.SCHEMATA
			  WHERE[SCHEMA_NAME] = 'f'
			  )
exec('CREATE SCHEMA f')
;
GO 
IF NOT EXISTS (SELECT [SCHEMA_NAME]
              FROM GHGandAGR.INFORMATION_SCHEMA.SCHEMATA
			  WHERE[SCHEMA_NAME] = 'vw'
			  )
exec('CREATE SCHEMA vw')